FROM cmelab/gpuconda:latest

ADD . /gixstapose

WORKDIR /gixstapose

# Install in base environment
RUN conda env update -n base -f environment.yml && \
    conda clean --all --yes -f && \
    python setup.py install

WORKDIR /home
